### ISSUE TITLE
why not instanceof ?

### ISSUE THREAD

**Issue by stevenvachon** [ljharb/is-string#1]
This is what I'd always used:
```js
return typeof str === "string" || str instanceof String === true;
```

**Comment by ljharb** [comment]
That won't work with cross-realm Strings - ie, from another `window`, ie, another realm. `instanceof` is simply *never* reliable and should generally be avoided.

**Comment by stevenvachon** [comment]
Thanks. Not reliable with same-realm `String`, though? I've never had a problem with it, except for Arrays.

**Comment by stevenvachon** [comment]
Did some reading.. now I know why people do weird-looking string things with Arrays/Objects. Fortunately, I've always avoided working with popups/iframes/frames.

**Comment by ljharb** [comment]
It's somewhat reliable with same-realm objects, but I could construct an object that is not a string but would pass your `instanceof` test, since it just checks the prototype chain - where as `Object#toString` exposes an internal slot that is otherwise hidden.

**Comment by stevenvachon** [comment]
Thanks for this info. It led to my collaboration in [is-plain-object](https://github.com/jonschlinkert/is-plain-object).
