### ISSUE TITLE
use "is-browser" package

### ISSUE THREAD

**Issue by stevenvachon** [ljharb/is-string#2]
Because node/io does not need cross-realm support. All that a server environment needs is:
```js
return typeof value==="string" || value instanceof String===true;
```

**Comment by stevenvachon** [comment]
Or, have two files in the release: client.js and server.js

**Comment by ljharb** [comment]
You're incorrect - node does need cross-realm support. See the `vm` core module.

**Comment by ljharb** [comment]
Related to #1
