### ISSUE TITLE
why does this even exist

### ISSUE THREAD

**Issue by Ratismal** [ljharb/is-string#7]

**Comment by Gedyy** [comment]
U

**Comment by ljharb** [comment]
because `typeof new String('f')` is `object`, and because `instanceof String` doesn't work cross-realm.

**Comment by Ratismal** [comment]
But the question remains; assuming that instantiated String objects are a thing that exist in your codebase, why does this exist when could easily do `typeof str === 'string' || str instanceof String`? I'm legitimately curious about the justification.

Out of scope and pedantic, but `new String('f')` is completely redundant since you're using a string to instantiate a string :eyes:

**Comment by ljharb** [comment]
That would return true for any object that coerced to a string - that’s not the same thing as “this object has the internal slots of a string”.

**Comment by Ratismal** [comment]
I see.

Well, from what you've told me, this library exists to serve an extremely obscure use case (using String instantiated objects *while also* cross-realm), and thus is pointless for most users. However, seeing as there still use a use case which can't easily be solved in a simple one-liner, my initial question of "why does this even exist" has been answered.

Thank you for your time. I hope you have a wonderful day.

**Comment by ljharb** [comment]
I agree it’s pointless for most users :-) luckily the criteria for “it should exist” is “its useful for any users”.

**Comment by mk-pmb** [comment]
It's valuable to have a package like this to easily express which kinds of strings you're testing for. An ad-hoc expression with typeof or even boolean operators would need additional documentation to clarify what aspects of it was intended and how much is just accidential. A package helps to externalize those docs, as well as the implementation details.
